version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: waf_user
      POSTGRES_PASSWORD: waf_password # Consider using secrets for production
      POSTGRES_DB: waf_db
    ports:
      - "5432:5432" # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
