services:
  dummy_web:
    build:
      context: ./dummy-web
    ports:
      - "5001:5001"
    networks:
      - waf_net

  waf:
    build:
      context: ./waf_proxy
    depends_on:
      - dummy_web
    environment:
      - GUNICORN_WORKERS=4
    networks:
      - waf_net

  admin_panel:
    build:
      context: ./waf_proxy
    command: gunicorn admin_dashboard:app -b 0.0.0.0:5005 -w 2 -k gthread --threads 2 --timeout 30
    depends_on:
      - waf
    networks:
      - waf_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "5005:5005"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - waf
    networks:
      - waf_net

networks:
  waf_net:
    driver: bridge