worker_processes auto;

events { worker_connections 1024; }

http {
    limit_req_zone $binary_remote_addr zone=waf_limit:10m rate=10r/s;

   
    server {
        listen 80;
        server_name localhost;
        
        
        return 301 https://$host$request_uri;
    }


    server {
        listen 443 ssl;
        server_name localhost;
        server_tokens off; 

     
        ssl_certificate /etc/nginx/ssl/waf.crt;
        ssl_certificate_key /etc/nginx/ssl/waf.key;
        
      
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            limit_req zone=waf_limit burst=20 nodelay;
            
        
            proxy_pass http://waf:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}